### PR TITLE
Implement delete members method

### PR DESCRIPTION
**Pull request by aivensong**
Implements `delete_members` method to delete members from a list in Responsys.

### CODE REVIEW

**Comment by lritter** [comment]
This should now work with slack.

**Comment by iamjwc** [comment]
I assume there are no tests for this repo. If there are can we add one?

**Comment by aivensong** [comment]
Added a test, ran locally and it looks like it's working...

**Comment by iamjwc** [comment]
Doesn't seem like a terribly effective test, but I know this library is a shit show. Does this actually hit the responsys servers?

**Comment by aivensong** [comment]
Looking at the other tests it seems like it should, but I can't seem to get my local tests working well enough to confirm. Not sure if anyone else has more experience running the tests in this repo.

**Comment by michaelyananimoto** [comment]
👍

**Pull request merged**
